[tool.poetry]
name = "decode"
version = "0.5.9"
description = "DESHIMA code for data analysis"
authors = [
    "Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>",
    "Tsuyoshi Ishida <tishida@ioa.s.u-tokyo.ac.jp>",
]
keywords = [
    "astronomy",
    "submillimeter",
    "spectroscopy",
    "deshima",
    "data-analysis",
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/deshima-dev/decode/"
documentation = "https://deshima-dev.github.io/decode/"

[tool.poetry.dependencies]
python = ">=3.6, <3.9"
astropy = "^4.1"
matplotlib = "^3.3"
netcdf4 = "^1.5"
numpy = "^1.19"
pyyaml = "^5.4"
scikit-learn = "^0.22"
scipy = "^1.5"
tqdm = "^4.62"
xarray = "^0.15"

[tool.poetry.dev-dependencies]
black = "^19.10b"
ipython = "^7.16"
myst-parser = "^0.15"
pydata-sphinx-theme = "^0.7"
pytest = "^6.2"
sphinx = "^3.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
